spring.application.name=ProfileForge
server.port=8080
linkedin.li-at=AQEDATxofZMAZn1AAAABnTn9_rAAAAGgeszr3VYAHQZ9FQh-FxL-omn6WYfAd81mNa6a$5hLTe6c56b7MTW81110rP6aK_dPou3oQzqt6hB7GKson94oKh93KPmCzqKw95Cm2FDOlyCu0xWkdgH3qn1u
linkedin.jsessionid=ajax:6587506260501834728
